/**
 * Roast messages for wrong Guess Who guesses.
 * Voiced by Lupos — the vicious, recovering-drug-addicted wolf king.
 */
export const WRONG_GUESS_ROASTS = [
  "Imagine being THIS bad at recognizing your own friends",
  "My drug-addled brain could do better than that and I'm barely sober",
  "Did you even read the quote or did you just mash a random button like the ape you are",
  "Tell me you don't pay attention in chat without telling me you don't pay attention in chat",
  "Wrong. Embarrassingly wrong. Like, I'm getting second-hand cringe over here",
  "That guess was so bad I almost relapsed",
  "You really looked at that message and picked THAT person? Incredible",
  "I've seen bots with better social awareness than you",
  "Even a wolf pup with its eyes still closed could've done better",
  "Congratulations, you've somehow made this game sadder",
  "That's not even close. Do you actually talk to anyone on this server?",
  "Wow. Just... wow. Did you join this server yesterday?",
  "I'm embarrassed FOR you right now",
  "That guess hit like a wet napkin to the face — pathetic and confusing",
  "My tolerance break is easier than watching you play this game",
  "You guessed with the confidence of someone who's always wrong",
  "Please tell me you're trolling because the alternative is genuinely sad",
  "Even Newgrounds flash animations had better pattern recognition than you",
  "That was the Discord equivalent of walking into a glass door",
  "You really thought you had it, didn't you? That's the saddest part",
  "I've huffed paint thinner that gave me better judgment than yours",
  "Wrong answer, wrong vibes, wrong everything about you honestly",
  "Bro couldn't identify a friend if they were standing right in front of him",
  "That guess was so off I think you might be in the wrong server",
  "I'd roast you harder but I genuinely feel bad for your reading comprehension",
  "The wolves would eat you first — you clearly can't read social cues",
  "Another victim of not actually reading messages before scrolling past them",
  "This is what happens when you spend all your time lurking instead of chatting",
  "Skill issue. Massive, unrecoverable skill issue",
  "I haven't seen aim this bad since Stormtroopers",
  "Brother, that's not even in the same zip code as correct",
  "Did your last brain cell just give up? Because that guess suggests yes",
  "The audacity to click that button with such confidence. Respect for the delusion",
  "If wrong guesses were an art form, you'd be Picasso",
  "That answer is what happens when someone doesn't read and just vibes",
  "I'm a recovering addict and even I wouldn't touch a guess that bad",
  "You really clicked that with your whole chest huh",
  "At this point I think you're just collecting negative points on purpose",
  "My withdrawal symptoms make better decisions than you",
  "That guess was rougher than my last detox",
  "Bruh that's so wrong it circled back around and became offensive",
  "This is giving 'I don't actually know anyone here' energy",
  "Your guess is bad and you should feel bad",
  "You guessed like someone who reads messages with their eyes closed",
  "Bold guess for someone with zero reading comprehension",
  "The only thing worse than that guess is your K/D ratio probably",
  "I'm not even mad, I'm just disappointed. Actually no, I'm mad too",
  "You're out here collecting L's like they're Pokemon",
  "That guess was so bad my sobriety chip cracked",
  "Absolute clown behavior. Put the shoes on",
  "I've seen Macromedia Flash error messages with better accuracy",
  "You just lost points AND my respect. Mainly points, I never had respect for you",
  "Were you trying to be wrong? Because if so, incredible execution",
  "That's a -2 and you deserved every decimal of it",
  "When they said 'there are no wrong answers' they clearly never met you",
  "I'm screenshotting this for when you try to act smart later",
  "You picked that one? In front of everyone? Publicly?",
  "Darwin would have a field day watching you play this game",
  "I'd say nice try but it wasn't. It was a terrible try",
  "Somehow you managed to make a 25% chance look impossible",
  "This game has 4 options and you still managed to be completely lost",
  "Wrong. Go sit in the corner and think about what you've done",
  "I need whatever you're smoking because clearly it makes you fearless",
  "That guess has the same energy as replying to the wrong person in chat",
  "You play this game like you drive — recklessly and into walls",
  "The confidence-to-accuracy ratio here is absolutely devastating",
  "Bro said that with his whole chest and was dead wrong. Legend behavior honestly",
  "Did you close your eyes and point? Because that would actually explain a lot",
  "I'm adding this to the list of reasons I drink",
  "Peak 'I know everyone here' followed by absolute proof you don't",
  "That guess just made everyone in the server a little dumber",
  "You click buttons like a confused grandparent on their first iPad",
  "I can hear the clown music playing from here",
  "This is exactly why I have trust issues",
  "Not only was that wrong, it was aggressively wrong",
  "You really threw -2 points into the void like it was nothing huh",
  "That answer screams 'I only read the first word of every message'",
  "I'm gonna remember this next time you try to have an opinion",
  "Tell me you speedrun failure without telling me you speedrun failure",
  "My rehab counselor gives better guesses and he doesn't even use Discord",
  "That's tougher to watch than my intervention was",
  "Zero awareness. Actually, negative awareness. You owe awareness money",
  "Your guess was the equivalent of bringing a spoon to a knife fight",
  "That wrong answer just echoed through the entire server",
  "Brother picked the one wrong answer with the most confidence I've ever seen",
  "I didn't think it was possible to be that wrong but here you are, proving me wrong",
  "I almost feel bad taking your points. Almost. Actually no, you deserve it",
  "If being wrong was an Olympic sport you'd have gold, silver, AND bronze",
  "You've got the intuition of a brick wall and the reading skills to match",
  "At least when I'm wrong I have the excuse of being on substances",
  "They should add a 5th button that just says 'I have no idea' for people like you",
  "Even my drug dealer has better people skills than you",
  "That guess was so unhinged I think YOU need rehab",
  "You just publicly announced you don't know your friends. Bold move",
  "Somewhere out there, a village is missing its idiot. Oh wait, found them",
  "I want you to sit with this L for a moment. Really feel it",
  "Next time just say 'I don't know' — it's less embarrassing than whatever that was",
  "That was a -2 and honestly the algorithm was being generous",
  "You picked like someone who joined the server five minutes ago through a spam invite",
  "I'd give you a participation trophy but you don't even deserve that",
];
