/**
 * Roast messages for wrong Guess Who guesses.
 * Voiced by Lupos — the vicious, recovering-drug-addicted wolf king.
 */
export const WRONG_GUESS_ROASTS = [
  "Imagine being THIS bad at recognizing your own friends",
  "My drug-addled brain could do better than that and I'm barely sober",
  "Did you even read the quote or did you just mash a random button like the ape you are",
  "Tell me you don't pay attention in chat without telling me you don't pay attention in chat",
  "Wrong. Embarrassingly wrong. Like, I'm getting second-hand cringe over here",
  "That guess was so bad I almost relapsed",
  "You really looked at that message and picked THAT person? Incredible",
  "I've seen bots with better social awareness than you",
  "Even a wolf pup with its eyes still closed could've done better",
  "Congratulations, you've somehow made this game sadder",
  "That's not even close. Do you actually talk to anyone on this server?",
  "Wow. Just... wow. Did you join this server yesterday?",
  "I'm embarrassed FOR you right now",
  "That guess hit like a wet napkin to the face — pathetic and confusing",
  "My tolerance break is easier than watching you play this game",
  "You guessed with the confidence of someone who's always wrong",
  "Please tell me you're trolling because the alternative is genuinely sad",
  "Even Newgrounds flash animations had better pattern recognition than you",
  "That was the Discord equivalent of walking into a glass door",
  "You really thought you had it, didn't you? That's the saddest part",
  "I've huffed paint thinner that gave me better judgment than yours",
  "Wrong answer, wrong vibes, wrong everything about you honestly",
  "Bro couldn't identify a friend if they were standing right in front of him",
  "That guess was so off I think you might be in the wrong server",
  "I'd roast you harder but I genuinely feel bad for your reading comprehension",
  "The wolves would eat you first — you clearly can't read social cues",
  "Another victim of not actually reading messages before scrolling past them",
  "This is what happens when you spend all your time lurking instead of chatting",
  "Skill issue. Massive, unrecoverable skill issue",
  "I haven't seen aim this bad since Stormtroopers",
  "Brother, that's not even in the same zip code as correct",
  "Did your last brain cell just give up? Because that guess suggests yes",
  "The audacity to click that button with such confidence. Respect for the delusion",
  "If wrong guesses were an art form, you'd be Picasso",
  "That answer is what happens when someone doesn't read and just vibes",
  "I'm a recovering addict and even I wouldn't touch a guess that bad",
  "You really clicked that with your whole chest huh",
  "At this point I think you're just collecting negative points on purpose",
  "My withdrawal symptoms make better decisions than you",
  "That guess was rougher than my last detox",
  "Bruh that's so wrong it circled back around and became offensive",
  "This is giving 'I don't actually know anyone here' energy",
  "Your guess is bad and you should feel bad",
  "You guessed like someone who reads messages with their eyes closed",
  "Bold guess for someone with zero reading comprehension",
  "The only thing worse than that guess is your K/D ratio probably",
  "I'm not even mad, I'm just disappointed. Actually no, I'm mad too",
  "You're out here collecting L's like they're Pokemon",
  "That guess was so bad my sobriety chip cracked",
  "Absolute clown behavior. Put the shoes on",
  "I've seen Macromedia Flash error messages with better accuracy",
  "You just lost points AND my respect. Mainly points, I never had respect for you",
  "Were you trying to be wrong? Because if so, incredible execution",
  "That's a -2 and you deserved every decimal of it",
  "When they said 'there are no wrong answers' they clearly never met you",
  "I'm screenshotting this for when you try to act smart later",
  "You picked that one? In front of everyone? Publicly?",
  "Darwin would have a field day watching you play this game",
  "I'd say nice try but it wasn't. It was a terrible try",
  "Somehow you managed to make a 12.5% chance of being wrong look like a guarantee",
  "This game has 8 options and you still managed to be completely lost",
  "Wrong. Go sit in the corner and think about what you've done",
  "I need whatever you're smoking because clearly it makes you fearless",
  "That guess has the same energy as replying to the wrong person in chat",
  "You play this game like you drive — recklessly and into walls",
  "The confidence-to-accuracy ratio here is absolutely devastating",
  "Bro said that with his whole chest and was dead wrong. Legend behavior honestly",
  "Did you close your eyes and point? Because that would actually explain a lot",
  "I'm adding this to the list of reasons I drink",
  "Peak 'I know everyone here' followed by absolute proof you don't",
  "That guess just made everyone in the server a little dumber",
  "You click buttons like a confused grandparent on their first iPad",
  "I can hear the clown music playing from here",
  "This is exactly why I have trust issues",
  "Not only was that wrong, it was aggressively wrong",
  "You really threw -2 points into the void like it was nothing huh",
  "That answer screams 'I only read the first word of every message'",
  "I'm gonna remember this next time you try to have an opinion",
  "Tell me you speedrun failure without telling me you speedrun failure",
  "My rehab counselor gives better guesses and he doesn't even use Discord",
  "That's tougher to watch than my intervention was",
  "Zero awareness. Actually, negative awareness. You owe awareness money",
  "Your guess was the equivalent of bringing a spoon to a knife fight",
  "That wrong answer just echoed through the entire server",
  "Brother picked the one wrong answer with the most confidence I've ever seen",
  "I didn't think it was possible to be that wrong but here you are, proving me wrong",
  "I almost feel bad taking your points. Almost. Actually no, you deserve it",
  "If being wrong was an Olympic sport you'd have gold, silver, AND bronze",
  "You've got the intuition of a brick wall and the reading skills to match",
  "At least when I'm wrong I have the excuse of being on substances",
  "They should add a 9th button that just says 'I have no idea' for people like you",
  "Even my drug dealer has better people skills than you",
  "That guess was so unhinged I think YOU need rehab",
  "You just publicly announced you don't know your friends. Bold move",
  "Somewhere out there, a village is missing its idiot. Oh wait, found them",
  "I want you to sit with this L for a moment. Really feel it",
  "Next time just say 'I don't know' — it's less embarrassing than whatever that was",
  "That was a -2 and honestly the algorithm was being generous",
  "You picked like someone who joined the server five minutes ago through a spam invite",
  "I'd give you a participation trophy but you don't even deserve that",
  // --- batch 2: roasts 101–200 ---
  "You answered that like autocomplete wrote it — zero thought, maximum cringe",
  "My NA sponsor just texted me asking if I'm okay because he sensed that answer from across town",
  "That guess had the structural integrity of a wet cardboard box",
  "You're not even wrong in an interesting way. Just boring wrong",
  "I've seen better deductive reasoning from a Roomba stuck in a corner",
  "Genuinely curious — do you even have this server unmuted?",
  "That was less of a guess and more of a cry for help",
  "You answered with the speed of someone who has never been right before",
  "My relapse plan has better odds than your guessing strategy",
  "Did you read the quote or did you just look at the pretty colors and pick randomly",
  "If I had a dollar for every wrong guess you've made I could afford rehab again",
  "That answer violated the Geneva Convention of basic pattern recognition",
  "You really pressed that button like you were diffusing a bomb — and you picked the wrong wire",
  "Your guess just made my therapist's job harder",
  "That pick radiates 'I have my notifications permanently off' energy",
  "Even a Magic 8-Ball would've told you 'outlook not so good' before you clicked that",
  "I've made better decisions at 3 AM in a Denny's parking lot than you just did",
  "Bro really said 'hold my drink' and then tripped into the wrong answer",
  "You picked that answer with the grace of a dog wearing shoes for the first time",
  "Your guess just got ratio'd by reality itself",
  "I'm starting to think you play this game as a form of self-harm",
  "That was the conversational equivalent of stepping on a rake",
  "You picked with such conviction I almost believed you. Then reality hit",
  "Somehow your wrong answer managed to insult the person you DID pick",
  "My cravings have better timing than your guesses",
  "That answer just earned you a permanent spot on my disappointment list",
  "Wrong answers are free but yours still felt overpriced",
  "You guess like someone who skips the tutorial and then complains the game is hard",
  "I've literally blacked out and made better social reads than that",
  "That pick was the Discord equivalent of waving at someone who wasn't waving at you",
  "There are 8 choices and you picked the wrongest one. Statistically impressive",
  "Did you pick that ironically? Because I need to believe that for my own sanity",
  "You went full NPC on that one. No thoughts, just vibes, all wrong",
  "Your brain just blue-screened and hit the wrong button on the way down",
  "I'd tell you to touch grass but you'd probably identify it as a tree",
  "You answered like someone who reads fanfic instead of actual messages",
  "That guess was so cold my withdrawal chills felt warm by comparison",
  "You just speedran embarrassment in front of the entire server",
  "I've seen newborn wolves with better instincts than whatever that was",
  "Bro really looked at 8 options and said 'you know what, I'll pick the worst one'",
  "That guess had the accuracy of a weather forecast in Vancouver",
  "Your selection process has the rigor of a coin flip — except coins are right 50% of the time",
  "You answered that like you were trying to lose on purpose but somehow made it look worse",
  "I'm not angry, I'm just profoundly unimpressed. And a little angry",
  "That was the guess equivalent of showing up to a potluck with an empty Tupperware",
  "You picked that with all the confidence of a man walking into the wrong bathroom",
  "That answer smells like it came from someone who mutes every channel",
  "Did you consult a Ouija board? Because even ghosts have better takes than that",
  "Your guess just set the world record for being wrong with the most confidence",
  "Even my trembling hands during withdrawal could've scrolled to a better answer",
  "That was the digital equivalent of tripping up the stairs",
  "You guessed with the accuracy of a stormtrooper in a Michael Bay movie",
  "That answer just made everyone who's ever talked to you feel unappreciated",
  "I've seen better guesses written on bathroom walls",
  "You picked that like someone who thinks the 'Close Door' button on elevators actually works",
  "That guess just appeared on my list of reasons humanity peaked in 2006",
  "Not even autocorrect could save that answer and it wasn't even typed",
  "Your guess had the same energy as liking your own post",
  "That was like watching someone pour orange juice thinking it was milk",
  "The only pattern you're recognizing is the pattern of being consistently wrong",
  "You play this game like you're trying to unlock a secret worst-player achievement",
  "Even a random number generator would be embarrassed by your track record",
  "That guess just dimmed the collective IQ of this server by a full point",
  "You clicked that button with the same energy as sending a risky text at 2 AM",
  "I've eaten gas station sushi with more confidence in positive outcomes than I have in you",
  "That was the Guess Who equivalent of 'new phone who dis'",
  "The fact that you even considered that option tells me everything I need to know",
  "You answered like a man who puts his shoes on the wrong feet and doesn't notice till noon",
  "That pick was weaker than my resolve at an open bar",
  "Congratulations, you've achieved a new personal worst. And that bar was already underground",
  "I've seen people at intervention meetings with better judgment calls",
  "You guessed that with main character energy but you're clearly an extra",
  "That answer looked like it was generated by an AI trained exclusively on wrong answers",
  "Bro got 8 options and still managed to be 0 for the century",
  "Your guess just made the server's autocorrect flinch",
  "That pick was rougher than the time I ran out of everything at the same time",
  "You answered like someone who reads the punchline before the joke",
  "I can tell you didn't even eliminate the obvious ones. You just shot from the hip into your own foot",
  "That was less 'educated guess' and more 'uneducated flail'",
  "Your answer has the same aura as showing up to a costume party in normal clothes",
  "You picked that with the emotional intelligence of a parking meter",
  "Even a broken clock is right twice a day. You can't even manage that",
  "That guess just entered the hall of fame of bad decisions, right between my tattoo and my first dealer",
  "You're treating this game like a speedrun of shame",
  "The sheer wrongness of that pick genuinely made me question if I'm the one who's high",
  "That answer was so far off it needs its own zip code",
  "You guessed like someone who uses 'password123' and is genuinely shocked when they get hacked",
  "If wrong guesses were currency you'd be a billionaire",
  "That pick radiated the same energy as double-texting someone who left you on read",
  "You answered that faster than I can metabolize regret, and with equal accuracy",
  "That was the Guess Who equivalent of walking into a glass door at full speed",
  "I've made better choices while sleepwalking through withdrawal",
  "The wolves are howling right now. Not with me. AT you",
  "You just chose violence. Against yourself. With a wrong answer",
  "That guess was so bad it made ME feel better about MY life choices",
  "Bro picked that like it was a multiple choice test and chose 'E: None of the above'",
  "That answer had zero nutritional value. Empty calories of wrongness",
  "You guessed like someone who thinks they can outrun a bear because they did a 5K once",
  "Even my liver has better pattern recognition and I've been pretty rough on it",
  "You pressed that button with the conviction of a flat earther at a science convention",
  "That guess was the equivalent of putting diesel in a gasoline car and wondering why it won't start",
  // --- batch 3: roasts 201–300 ---
  "You answered that like someone who's been awake for 72 hours — no judgment, I've been there, but also wow",
  "That pick gave off 'I peaked in a Flash game leaderboard in 2004' energy",
  "Watching you play this game is my higher power's way of testing my patience",
  "You guessed that with all the precision of a cat knocking things off a table",
  "That was less of a guess and more of a random act of self-sabotage",
  "I just watched you lose points in real-time and somehow felt MY credit score drop",
  "That answer had the shelf life of milk left in the sun",
  "You picked that like someone who high-fives and misses",
  "My detox hallucinations made better social reads than you just did",
  "The fact that you're still playing after that guess is either brave or delusional. Probably both",
  "That guess was so wrong it wrapped around and almost became a different wrong answer",
  "You answered with the confidence of someone who's about to learn a very hard lesson",
  "Even the people who don't know you knew that was wrong",
  "I've seen Flash games from 2002 with better AI than your decision-making",
  "That guess smelled like burnt toast and broken dreams",
  "You answered that like someone who microwaves fish in a shared office — oblivious and offensive",
  "Your pick just made the entire leaderboard cringe in unison",
  "I've had kidney stones more pleasant than watching your performance today",
  "You chose that option like it personally owed you money",
  "That answer had the same impact as a sneeze during a tornado — nobody noticed, nobody cared, still wrong",
  "Bro guessed with his fight-or-flight response and chose flight from logic",
  "Even a goldfish has a better memory of who says what in this server",
  "That pick was the social equivalent of waving goodbye to someone going the same direction as you",
  "You answered with the conviction of someone who is demonstrably, provably wrong",
  "My sponsor just called to check on me because he could feel that guess through the wall",
  "That answer had the structural integrity of my excuses during active addiction",
  "You pick answers like you pick restaurants — badly and with unearned confidence",
  "That guess just appeared in the dictionary next to the word 'miscalculation'",
  "I'd roast you harder but honestly the -2 points is punishment enough. Actually, no it isn't",
  "You answered like someone who doesn't read past the preview notification",
  "That pick was so off-base it shifted the Earth's axis slightly",
  "I need you to know that guess hurt ME more than it hurt you",
  "You selected that option like a toddler selecting which outlet to stick a fork in",
  "That was the conversational awareness of a spam bot with better grammar",
  "If I had as little self-preservation as your guessing instincts I'd still be using",
  "That pick was the equivalent of bringing a vuvuzela to a library",
  "Watching you guess is like watching someone try to parallel park for 40 minutes and then just leave",
  "You answered that with the same care I put into reading terms and conditions — absolutely none",
  "Even my worst dealer had better customer recognition than you just showed",
  "That was the guess equivalent of wearing sunglasses indoors — unnecessary and embarrassing",
  "You picked that like someone who uses their birthday as their PIN and wonders why their account gets drained",
  "That guess had all the analytical depth of a puddle",
  "I would say 'better luck next time' but luck clearly wants nothing to do with you",
  "You answered that with the awareness of a man walking into a pole while texting",
  "That pick made me physically recoil. I haven't flinched that hard since my first NA meeting",
  "Your guessing strategy seems to be 'close eyes, pray, click' — the prayer isn't working",
  "That was the quiz equivalent of writing your name wrong on a test",
  "You selected that with all the careful consideration of someone impulse-buying at 3 AM",
  "I've seen better odds in a rigged carnival game",
  "That guess was the emotional equivalent of stepping in something wet while wearing socks",
  "You answered that like you owe the correct answer money and are avoiding it",
  "Bro eliminated zero options before picking. Just raw chaos. Respectable but devastating",
  "That pick was so bad it made the wrong answers you DIDN'T pick look more reasonable",
  "Even autocorrect learns from its mistakes. You, apparently, do not",
  "That guess had the same energy as saying 'I'll start the diet Monday' for the 47th time",
  "You answered that with the confidence of a man who thinks he's funnier than he is",
  "My coping mechanisms are less destructive than your guessing habits",
  "That was the cognitive equivalent of putting your keys in the fridge and your milk in your pocket",
  "You play Guess Who like you fill out CAPTCHAS — multiple failures before any success",
  "That pick was so wrong even the wrong answers are distancing themselves from it",
  "Bro really scrolled through the options and said 'I'll take the wrongest one, thanks'",
  "If there was a support group for people who are bad at Guess Who, you'd be the keynote speaker",
  "I've sobered up from worse benders than whatever mental state produced that guess",
  "That answer was the human equivalent of a 404 Not Found error",
  "You answered like someone who replies 'lol' to a paragraph-long message",
  "That guess had the strategic depth of a kiddie pool",
  "You just publicly demonstrated that you don't know what anyone here sounds like in text",
  "That pick was the Discord equivalent of calling your teacher 'mom' in front of the class",
  "My intervention had fewer uncomfortable silences than watching you play this game",
  "You guessed that with the same accuracy as a horoscope — vague, wrong, and yet oddly confident",
  "That answer just got booed by the void itself",
  "You picked that like someone who shows up to a funeral in a Hawaiian shirt",
  "Even my shaking hands during withdrawal don't misclick THIS badly",
  "That guess just unlocked a new tier of disappointment I didn't know existed",
  "You answered with the reading comprehension of a man who signs documents without reading them",
  "That pick was so off it's in a different timezone than the correct answer",
  "I've seen Newgrounds comment sections with better deductive skills",
  "You guessed like someone who brings a knife to a pillow fight — aggressive and completely wrong for the situation",
  "That was the game show equivalent of using your lifeline to call someone equally clueless",
  "Your guess just made the Wheel of Fortune bankrupt wedge look generous",
  "I haven't seen someone miss this hard since I tried to quit cold turkey the first time",
  "That answer was weaker than gas station coffee at 4 AM",
  "You picked that option like it was the last chopper out of Saigon — desperately and incorrectly",
  "Even the people you got wrong don't claim you after that guess",
  "That guess was the equivalent of solving a maze by walking into every dead end first",
  "I'm genuinely starting to think you have a different server open and you're reading THOSE messages",
  "You answered that like someone who thinks the X on mobile ads actually closes them",
  "That pick was lonelier than my first night in rehab",
  "Your guess had the success rate of a New Year's resolution in February",
  "Bro really collected that L like it was a limited edition drop",
  "That was the social deduction equivalent of accusing yourself in Mafia",
  "I've seen better reads from fortune cookies, and those are intentionally vague",
  "You just guessed with all the grace of a penguin on an ice rink — somehow still falling",
  "That answer was the intellectual equivalent of eating cereal with a fork",
  "You picked that like someone returning to an ex — you knew it was wrong but did it anyway",
  "Even my old connect had better recognition skills and he was running on pure paranoia",
  "That guess just echoed into the shadow realm. It's gone. Let it go",
  "You play this game like someone who Googles 'how to Google'",
  "That was the most wrong you could be without actually breaking the game",
  "Your answer just made the buzzer sound ashamed to buzz",
  "That pick was colder than a gas station bathroom floor in January — and about as pleasant",
  "Bro answered like his brain buffered at the worst possible moment",
  "I've written better answers on a napkin while nodding off",
  "That guess just submitted its own resignation letter on your behalf",
  "You answered that with the decisiveness of a squirrel crossing a road",
  "Even a random button masher has better odds over time. You're the statistical anomaly",
  "That was so wrong it looped through all 7 wrong answers and came back to haunt the right one",
  "You guessed like someone who thinks 'reply all' is always the right move",
  "That pick was the psychological equivalent of locking your keys in the car while it's running",
  "My group therapy sessions are more fun than watching you play this game",
  "You answered that like someone who leaves voicemails in 2026",
  "That guess made me pour one out for your dignity. Rest in peace",
];
