const ignorePhrases = [
    "Strange... was that a voice or just my imagination?",
    "Did someone say something? Must've been the air conditioning.",
    "Huh, thought I heard a noise. Anyone else catch that or just me?",
    "Was that a person talking or just the pipes creaking?",
    "Did y'all hear something just now? Probably just the building settling.",
    "Weird, sounded like someone spoke. Must be hearing things.",
    "Anyone else pick up on that sound? Could've been from outside.",
    "Did I just hear talking or was that the TV from next door?",
    "That's odd... did someone mumble something or am I going crazy?",
    "Was that a voice? Nah, probably just static or something.",
    "Did anyone catch that? Sounded like gibberish, must be the radio.",
    "Strange noise just then... anyone else notice or just my ears playing tricks?",
    "Thought I heard someone. Must be the neighbors being loud again.",
    "Was that speech? Eh, probably just background noise.",
    "Did something just make a sound? Maybe it's the ventilation system.",
    "Anyone else hear that whisper? Could be the wind through the window.",
    "Peculiar... sounded like words but probably just random sounds.",
    "Did someone try to speak? Must've been an echo from somewhere.",
    "That was bizarre, did anyone catch that or was it just interference?",
    "Heard something faint... anyone else or am I imagining things?",
    "Was that a person or just the floorboards making noise?",
    "Strange sound there... did y'all hear it too or just ambient noise?",
    "Someone say something? Nah, must be the traffic outside.",
    "Did I hear talking or was that just white noise?",
    "Odd... thought someone spoke. Probably just the fan humming.",
    "Anyone else notice that sound? Could be mice in the walls.",
    "Was that a voice I heard? Must be someone's phone in the distance.",
    "Did something just make noise? Maybe the heating kicked in.",
    "Thought I caught some words there... anyone else or just me hallucinating?",
    "Strange vibration in the air... did anyone feel that or hear something?",
    "Was someone trying to communicate? Probably just electrical interference.",
    "Did y'all pick up on that murmur? Could be coming from upstairs.",
    "Heard a weird sound... anyone else or is my hearing acting up?",
    "Was that human speech? Nah, probably just the dishwasher running.",
    "Something just made noise... did anyone catch what it was?",
    "Thought I heard a voice. Must be the podcast playing somewhere.",
    "Did anyone else hear that rumble? Probably just thunder in the distance.",
    "Strange... was that talking or just the washing machine?",
    "Anyone notice that sound? Could've been a car horn outside.",
    "Did someone whisper? Must be the trees rustling.",
    "Weird noise just happened... anyone else hear it or just my tinnitus?",
    "Was that a person speaking? Probably just the neighbor's TV.",
    "Did I catch some words there? Must be the radio bleeding through.",
    "Heard something odd... anyone else or am I losing it?",
    "Was that conversation? Nah, probably just people walking by outside.",
    "Strange sound... did y'all hear that too or was it just in my head?",
    "Someone make a noise? Could've been the door creaking.",
    "Did anyone else catch that mumbling? Probably the refrigerator humming.",
    "Thought I heard speech... must be echoes from the hallway.",
    "Was that a voice or just the house making its usual sounds?",
    // Techy phrases
    "Did my headset glitch or did someone try to talk? Must be a driver issue.",
    "Was that voice chat? Nah, probably just NPCs in the background.",
    "Strange... thought I heard someone. Maybe my Discord is bugging out.",
    "Did anyone else hear that? Could be my GPU fans acting up again.",
    "Was that a player or just ambient game dialogue?",
    "Weird audio artifact... anyone else get that or is my sound card dying?",
    "Did someone ping me? Must be notification sounds from another tab.",
    "Thought I heard comms... probably just the game's background chatter.",
    "Was that team chat? Nah, must be my Spotify bleeding through.",
    "Anyone else catch that noise? Maybe my mechanical keyboard is haunted.",
    "Did my cat just meow or did someone speak? Hard to tell sometimes.",
    "Strange sound in my headphones... probably need to update my drivers.",
    "Was that a real person or just an NPC barking orders?",
    "Did someone message me? Could be my phone buzzing on the desk.",
    "Heard something through the static... anyone else or is my WiFi acting up?",
    "Was that voice proximity chat? Must be coming from the other room.",
    "Did my parrot just mimic someone or was that actual speech?",
    "Weird audio glitch there... did y'all hear it or is my RAM failing?",
    "Someone in voice channel? Nah, probably just the loading screen music.",
    "Did anyone else's audio bug out? Could be packet loss.",
    "Thought I heard talking... must be my hamster wheel squeaking.",
    "Was that a player callout? Probably just the tutorial voice.",
    "Strange interference... anyone else or is my RGB setup causing issues?",
    "Did someone @ me? Must be the notification sound from Steam.",
    "Was that human speech or did my AI assistant randomly activate?",
    "Heard something in my turtle tank... wait, that's not right.",
    "Did the server just lag or did someone try to communicate?",
    "Was that a raid notification? Nah, probably just system sounds.",
    "Anyone else hear that beep? Could be my UPS battery warning.",
    "Did my dog just bark at nothing or was someone at the door?",
    "Strange noise in the server... probably someone's open mic picking up static.",
    "Was that a whisper or just my PC's coil whine?",
    "Did someone join the lobby? Must be the matchmaking sound effects.",
    "Weird audio pop... anyone else or do I need new thermal paste?",
    "Was that a player or did Alexa just randomly respond to something?",
    "Did my fish tank filter just gurgle or did someone speak?",
    "Thought I heard voice chat... must be the Twitch stream in background.",
    "Anyone else get that sound? Could be my router having a moment.",
    "Was that a real person or just my smartwatch giving notifications?",
    "Did someone hot mic? Nah, probably just electronic interference.",
    "Strange noise through my DAC... anyone else running into audio issues?",
    "Was that team comms or is my neighbor's bluetooth speaker bleeding through?",
    "Did my guinea pig just squeak or was that someone's mic?",
    "Heard something weird... probably my SSD making death noises.",
    "Was that a player or did the Google Home just malfunction?",
    "Anyone else catch that? Could be my PSU capacitors whining.",
    "Did someone try to DM me? Must be the Discord notification bug.",
    "Was that speech or just my laptop fan crying for help?",
    "Weird sound in my IEMs... did anyone say something or is it EMI?",
    "Did my snake's heat lamp just click or was that someone talking?"
];

module.exports = ignorePhrases;
